### ISSUE TITLE
Competitor plugin "completed area"

### ISSUE THREAD

**Issue by that0n3guy** [ivan-lednev/obsidian-task-archiver#1]
I've been using https://github.com/DahaWong/obsidian-completed-area for this functionality.  

Can you explain the difference between yours and that one?  Might be good to put the diff in your readme.

**Comment by ivan-lednev** [comment]
Hi, @that0n3guy,

thanks for the question! The plugin you linked to seems abandoned at an early stage. For now, my plugin is able to add completed tasks under the current week note, making it easy to get an overview of your weekly accomplishments:
![image](https://user-images.githubusercontent.com/41428836/132384962-59f0922c-1802-46d1-bd56-780e8963b8d8.png)

I'm planning to add more features from org-mode, like archiving tasks to a separate file. Soon, I'm going to lay out the development plan in a roadmap.
