### ISSUE TITLE
Archive To File Missing Traceability

### ISSUE THREAD

**Issue by 702573N** [ivan-lednev/obsidian-task-archiver#13]
If using the archive to separate file option, the appended tasks could not be assigned to the original note. Inside this archive file, the archiver plugin should create sub-headings based on the title of the original file. Under this sub-headings the archived tasks should be moved automatically. This could be a great way to built a big archive with structure and traceability.

Alternatively a backlink to the original note could be appended to the archived task.

**Comment by Unpreditable** [comment]
Another idea - Send completed tasks in multiple files to a single archive and separate them by file name headers or other way.
