### ISSUE TITLE
[Feature request] Regex to define action

### ISSUE THREAD

**Issue by pcause** [ivan-lednev/obsidian-task-archiver#15]
I have certain tasks that match a regex that I want to move to a separate file when completed and other that should be left alone.  I'd like to be able to give various regex and for each one define the action.  For example, I have a few tasks that are repeated daily.  When marked done they can be deleted or moved to a DONE file.  I could add a label {#daily) and then a regex that matches #daily and when that item is marked done it gets moved to the DONE file and the new task for the next day (which is not complete) is ready for the next day.

**Comment by ivan-lednev** [comment]
Hello, @pcause!

Thank you for your input! Check out 0.7.0. There is now a new setting to define a pattern for tasks that should be archived. So you can add `#daily` to some of them and only they're going to be moved.
