### ISSUE TITLE
Compatibility with Tasks Plugin

### ISSUE THREAD

**Issue by wealthychef1** [ivan-lednev/obsidian-task-archiver#16]
I'd like to specify that only tasks with the tag `#task` be affected by archiving operations.  This is a special case of issue https://github.com/ivan-lednev/obsidian-task-archiver/issues/15

**Comment by wealthychef1** [comment]
I have submitted a pull request that enables this feature...  https://github.com/ivan-lednev/obsidian-task-archiver/pull/18

**Comment by ivan-lednev** [comment]
Addressed in 0.7.0.
