### ISSUE TITLE
Strip tags from archived tasks

### ISSUE THREAD

**Issue by PrivacyWise** [ivan-lednev/obsidian-task-archiver#19]
First, thanks for this plugin. I'm finding it extremely useful and usable as I migrate from Taskpaper to Obsidian. 

One feature I'm missing from Taskpaper is that you can optionally strip tags off archived tasks so that they don't show up in the tag view or tag searches.

I can think of a few ways to go about it in the obsidian-task-archive:
1. just strip the tags off when archiving, like TP does
2. modify the tags when archiving, for example replace '#' with '@' so that you preserve the info but don't pollute the tag view or search.
3. Archive to a separate file, as already possible, but ignore that file in tag searches. I don't see that there's currently a way to do this in Obsidian, but if there was . . . 

So, any thoughts or recommendations? 

Or, I don't know that I'm capable of trying to code it myself and make a pull request, but if I were to try, where should I start?

Thanks!

DW

**Comment by ivan-lednev** [comment]
Hello, @PrivacyWise,

Thank you for your input! I addressed the issue in 0.8.0. Check out the settings tab to configure replacement.

**Comment by PrivacyWise** [comment]
@ivan-lednev , love it. I see it in the settings and am going to set it up right now. Thank you!
