### ISSUE TITLE
Feature: Other heading option for archieved tasks

### ISSUE THREAD

**Issue by bhickta** [ivan-lednev/obsidian-task-archiver#2]
This plugin only uses H1 heading for Archieved tasks but Some plugins like obsidian-filename-heading-sync uses H1 tag to rename the file hence; it conflicts with such plugins

Example: 
![image](https://user-images.githubusercontent.com/61617746/133545409-427df4b2-1ee5-4e2c-8961-781046d2fe64.png)
![image](https://user-images.githubusercontent.com/61617746/133545439-c42f96e0-35c3-48db-9f00-7ede704b2687.png)

Therefore having more than one Header option would be a great option

**Comment by ivan-lednev** [comment]
Hello @bhickta,
thank you for your input.

I added the option in the [new plugin version](https://github.com/ivan-lednev/obsidian-task-archiver/releases/tag/0.3.0).
