### ISSUE TITLE
Dealing with recurring tasks?

### ISSUE THREAD

**Issue by feedhopper** [ivan-lednev/obsidian-task-archiver#21]
Hi there,

your plugin is fantastic. It is an excellent solution to the task cluttering problem in Obsidian!

I wonder about one thing: how to deal with recurring tasks?
Of course, I am fine with the task ticked away being moved to my archiv file. But what about those that are supposed to come again on any given day?

**Comment by FabianoLothor** [comment]
@feedhopper I don't know what's the task plugin that you're using.

But if you're using https://github.com/obsidian-tasks-group/obsidian-tasks than you don't have to worry about that, since a new task is automatically created when you complete the previous one.

The archive only archives completed tasks, so...

**Comment by ivan-lednev** [comment]
Hi @feedhopper! @FabianoLothor is right. `obsidian-tasks` duplicates recurring tasks once you complete them: 
![image](https://user-images.githubusercontent.com/41428836/218692357-98126595-74ac-4e30-8a98-e5c4370edd94.png)

My plugin is not going to touch the original unchecked task.

**Comment by reagle** [comment]
Thank you for the great plugin! Could this be re-opened? I'd like a single command/hotkey to mark an obsidian-tasks completed.

1. when I use your "Toggle task done an archive it"; no new recurring event is created in its place.
2. when I use Obsidian Task: "Toggle task done," I then need to run your "Archive Tasks in this File".

BTW: Is there a way to archive tasks throughout the vault?

**Comment by montemartin** [comment]
@reagle if you are still looking for a solution this check out the [Better Command Palette](obsidian://show-plugin?id=obsidian-better-command-palette). It has a macro's feature that allows you to chain commands together into a single command.
