### ISSUE TITLE
For some notes, tasks are removed and not appended to the archive

### ISSUE THREAD

**Issue by alexlyzhov** [ivan-lednev/obsidian-task-archiver#24]
I have "Archive to a separate file" set to true. When I select the archive tasks command, for many notes (maybe half of my notes) Obsidian writes an error msg "Error: file already exists" in the upper right corner, and completed tasks are just removed instead of being removed and then appended to the file with the corresponding task archive.

I've checked and the name of the note where the tasks to archive are located matches the name of the file with the task archive for the note. There's nothing special about the file with the task archive, it's writable, etc. Not sure why this happens.

**Comment by alexlyzhov** [comment]
This is happening on the latest version.

**Comment by ivan-lednev** [comment]
Hello, @alexlyzhov, thank you for your input! I need more information to reproduce the issue. Could you provide the following info:
1. The name of the file with completed tasks
2. The command you use
3. The name of the archive
4. What value you have in the archiver options here: 
![image](https://user-images.githubusercontent.com/41428836/209832093-631ea214-f205-4527-9045-369bca35cac9.png)

**Comment by alexlyzhov** [comment]
1. `003 Resources/Scratchpad`
2. `Archiver: Archive tasks in this file`
3. `Other/Completed tasks/Task archive Scratchpad`
4. Archive to separate file: on. Separate archive file name: `Other/Completed Tasks/Task archive %`.

I found the issue—it was because of the lowercase/uppercase mismatch in the archive file path (`Completed tasks` / `Completed Tasks`). After fixing the folder name I think the plugin started working.
