### ISSUE TITLE
[feature request] Archive tasks in their correct completed dates instead of use the date that a task was archived

### ISSUE THREAD

**Issue by FabianoLothor** [ivan-lednev/obsidian-task-archiver#26]
These are my current settings:

![image](https://user-images.githubusercontent.com/2192995/210464293-cbbe9ea5-6d4d-4770-a800-0f7da08262d5.png)

Now imagine that I have these tasks:

![image](https://user-images.githubusercontent.com/2192995/210464336-2ed8dc79-9811-4ce6-9d80-d3c7277c34b4.png)

I am using https://github.com/obsidian-tasks-group/obsidian-tasks plugin.

As you can see, the plugin automatically adds the `done date` to the end of the task line.

It would be great if the Obsisian Task Archiver could identify the `done date` and archive the tasks to their correct dates.

If I archive the mentioned tasks, I'll get the following behavior:

![image](https://user-images.githubusercontent.com/2192995/210464546-79aaff22-d819-425c-9f49-6588cc1f4a9f.png)

While my expected behavior is:

![image](https://user-images.githubusercontent.com/2192995/210464609-82a97a9a-b80e-42c8-84ae-3c45a862a8e9.png)

**Comment by FabianoLothor** [comment]
I understand that it's an odd request, since it's using a feature of a third party plugin.

I would suggest to create an option to enable/disable the feature.

And instead of rely on the third party plugin, the rule would be:
- "try to find the last date present in the task-line and use it when archiving, if there isn't a date, use the current date when archiving"

**Comment by galsom** [comment]
First of all, thank you for the wonderful add-on 👍 

I use a combination of Task Archiver and Tasks as well and have the same request.

Some of my projects are longer running and currently have a long list of archived tasks that are not sorted by any means.

Hopefully this can become possible.
