### ISSUE TITLE
The empty new line after the Archived heading...

### ISSUE THREAD

**Issue by uwidev** [ivan-lednev/obsidian-task-archiver#3]
Is that supposed to be there? It's kind of tripping me over; literally unplayable.

![literally_unplayable.jpeg](https://user-images.githubusercontent.com/10101319/133907556-e8fd3e40-3c18-4eb0-a0d7-a744e5ee3fd5.png)

**Comment by blongty** [comment]
I also wanted to give you my appreciation for creating this plugin. It's something I've manually been using ever since I've used the Tasks plugin. This completes it (and me).

**Comment by ivan-lednev** [comment]
Hello, @uwidev,

thank you for your kind words. They really mean a lot to me. 

I added the option you requested in the [new plugin version](https://github.com/ivan-lednev/obsidian-task-archiver/releases/tag/0.3.0).
