### ISSUE TITLE
Feature request: Move completed items automatically

### ISSUE THREAD

**Issue by YousufSSyed** [ivan-lednev/obsidian-task-archiver#30]
I would like that as soon as I check a task as complete, it moves automatically to the archive page.

**Comment by ivan-lednev** [comment]
Hello, @YousufSSyed! Thank you for your input! There is a new command in 0.10.0 that allows you to complete and archive a task under cursor (Toggle task done and archive it)

**Comment by YousufSSyed** [comment]
@ivan-lednev How exactly do I use it? Do I just run the command for each task I want to mark as complete?

What I want is for it to automatically archiv my tasks when I click the checkbox with my mouse.

**Comment by ivan-lednev** [comment]
@YousufSSyed, you can assign some hotkey to the command (e.g. ctrl + Enter), this way when the caret is on a line that contains a task, you press your hotkey, and the task is going to get checked & archived.

I'll reopen the ticket and investigate a way to do it the way you described.

**Comment by pcause** [comment]
since the tasks plugin now has statuses, just clicking will archive tasks that I move to a "in progress" state and aren't completed.  perhaps make this "when I click and the task is completed ('x') is set as status".

**Comment by YousufSSyed** [comment]
@pcause Are you saying you archive tasks with the Tasks plugin?

**Comment by pcause** [comment]
No.  I am saying that in your plugin you can't rely on click as was suggested.  tasks and other plugins use other symbols to indicate various states that are not "done".  Done means an x in the box.  What I was saying is nthat you have to see what the value in the box is set to before archiving.

**Comment by Ambioid** [comment]
Seconded, I think that it would be beneficial for the achiver to automatically trigger when I tick a box, rather than needing to be triggered manually every time.
