### ISSUE TITLE
Feature Request: allow for moving different task patterns to different pages

### ISSUE THREAD

**Issue by YousufSSyed** [ivan-lednev/obsidian-task-archiver#31]
I would like to move cancelled tasks items `[-]` to `% - Scrapped` pages (what I would write under "separate archive file name"), and completed task items `[x]` to `% - Archived` pages.

**Comment by ivan-lednev** [comment]
Hello @YousufSSyed,

Thank you for your input! Check out 0.16.1. You can now configure different files for different task statuses:
![image](https://user-images.githubusercontent.com/41428836/223450343-1f55c320-375c-4d9b-bf39-d4bc66eff562.png)

**Comment by ivan-lednev** [comment]
Hi, @YousufSSyed,

I tried it out with the settings you provided, and it worked as expected. Could you please share the file in which you ran the command and your settings file (`<your-vault>/.obsidian/plugins/obsidian-task-archiver/data.json`). Also check what you see in the console when you run the command (you can see it by pressing `F12`).

**Comment by YousufSSyed** [comment]
Before I thought of doing that, I uninstalled and reinstalled the plugin, and then manually changed all the settings to match the screenshot. It works now. 

Just so you know, a while ago I actually made a second copy of the plugin to handle [-] tasks, and created a macro with Better Command palette to run the archive tasks command from both copies. Maybe something happened when I copied it, idk.
