### ISSUE TITLE
I would live to archive tasks without specifying archive header text (without a header at all), especially when moving them to another note.

### ISSUE THREAD

**Issue by YousufSSyed** [ivan-lednev/obsidian-task-archiver#32]
I just want the tasks right on the page without being under a header.

**Comment by ivan-lednev** [comment]
Hello, @YousufSSyed!

I added such an option to 0.15.0:
![image](https://user-images.githubusercontent.com/41428836/222527179-1b43c337-d253-4e04-8780-04b7504288af.png)
