### ISSUE TITLE
[Feature request] Add heading information to archived task

### ISSUE THREAD

**Issue by lukepolak** [ivan-lednev/obsidian-task-archiver#33]
Currently, if I have multiple lists separated by headings, when I archive tasks in that page, information about section, in which that task was, is lost. I remember using something like that in sublime sometime ago, and it had this mechanism, that added context to archived elements, one of which was called @project(NAME OF PROJECT). In obsidian, it could be name of the heading, so if I archive something like this:

# Test project
- [x] Test task

It is then archived to this:
- [x] Test task @project(Test project)

Is this something within scope of this plugin or am I overextending it's functionality? :)

**Comment by ivan-lednev** [comment]
Hi, @lukepolak. Thank you for your input! I've added the `{{heading}}` placeholder in the latest version. This is how you can achieve the behavior you described:
![image](https://user-images.githubusercontent.com/41428836/222503540-485a5590-5a5d-4983-9041-b660faea4cb1.png)

**Comment by lukepolak** [comment]
That was fast :D Thanks a lot, great project :)

**Comment by bennotkin** [comment]
I'm very impressed by the speed this was resolved with! I wanted this feature, saw lukepolak's feature request, liked it, and it was implemented!

As you continue to develop this, it would be great to have access to multiple levels of headings – either by requesting a certain heading level or by going up the chain (e.g. {{heading-3}} or {{^heading}}

**Comment by ivan-lednev** [comment]
Hi, @bennotkin, 

Could you describe the use case here? Perhaps this will help me come up with a solution.

Requesting a certain heading level is tricky, since it would require some fallback for the case when there are no headings at this level.

Creating something like a `{{headingChain}}` is more straightforward:
```
# Heading 1
## Heading 2
### Heading 3

- [x] task

```
Will turn into 
```
# Archived

- [x] task (Heading 1 > Heading 2 > Heading 3)

```

**Comment by bennotkin** [comment]
A heading chain would probably be ideal.

An example use case: a person works on multiple teams with multiple projects, and they organize their tasks as follows.

```
# Team 1
## Project A
- [x] Task 1
- [ ] Task 2
- [ ] Task 3
## Project B
- [ ] Task 1
- [ ] Task 2
# Team 2
## Project A
- [ ] Task 1
- [x] Task 2
- [ ] Task 3
## Project B
- [x] Task 1
- [ ] Task 2
```

Would yield something akin to

```
# Archived
- [x] Task 1 (Team 1 > Project A)
- [ ]

**Comment by ivan-lednev** [comment]
Hi, @bennotkin,

I added a new placeholder in 0.22.0:
![image](https://user-images.githubusercontent.com/41428836/226938628-4dae6b6f-578b-486f-8199-b5b6a03ed48f.png)

**Comment by bennotkin** [comment]
As I continue to use this (again, thank you so much for your attentiveness and speed, as well as for the tool overall!), I think including the filename (or the the first header in the file) in all the headingChains seems silly when you're archiving to the same file. Obviously it's typically very helpful when archiving to a different file. It'd be nice, in a very low priority way, to either remove the filename from the chain when archiving to the same file, or to make that an option.
