### ISSUE TITLE
Archive to separate file within the same folder

### ISSUE THREAD

**Issue by tonyxiao** [ivan-lednev/obsidian-task-archiver#34]
When I archive tasks to separate files, obsidian archiver seems to create the said separate file in my vault root, regardless of whether or not I already have a file existing right next to the file i'm archiving properly named e.g. (`subfolder/my tasks (archive)` next to `subfolder/my tasks`. I'd like to archiver to look for a file with the same name (anywhere in the vault ideally, if not at least in the current directory) before creating new file.

**Comment by tonyxiao** [comment]
yay! Can I pull it from the latest release now?

**Comment by tonyxiao** [comment]
![CleanShot 2023-03-03 at 13 49 00](https://user-images.githubusercontent.com/696842/222641730-d29fda56-6b61-44d6-97de-70730445e3d7.gif)
Just got on version 0.15 and for some reason I can't toggle the button at all anymore.

**Comment by ivan-lednev** [comment]
Hi @tonyxiao, could you please share what you see in the obsidian developer console when you are pressing these buttons?
