### ISSUE TITLE
Customise task status for "Archive all checked tasks"

### ISSUE THREAD

**Issue by kmaustral** [ivan-lednev/obsidian-task-archiver#35]
At the moment, this is either for just [x] or any symbol between "[]. I am using the new status function in Tasks to set a different character for a completed task [&}. If you toggle for all symbols, then it also archives all other statuses, such as [i]. 

It would be good to be able to customise the symbols used.

**Comment by ivan-lednev** [comment]
Hello, @kmaustral,

Thank you for your input! Check out 0.16.1. Now you can create rules for different statuses:
![image](https://user-images.githubusercontent.com/41428836/223450092-8c8f994b-fd16-441e-bf84-c01425b529a0.png)

**Comment by kmaustral** [comment]
Thanks so much. It's all working now.
