### ISSUE TITLE
Archiver commands no longer available in command palette

### ISSUE THREAD

**Issue by benadamstyles** [ivan-lednev/obsidian-task-archiver#38]
Firstly, thanks so much for this plugin! I really miss it now that it's not working for me 😅 

I don't think I've done anything unusual, but since about a week or 2 ago, I can't use any archiver commands – they're simply not present in the command palette. Any idea why this could happen?

**Comment by ivan-lednev** [comment]
Hello @benadamstyles!

Some things to try:
1. Check if the plugin is still installed
2. Check if the plugin is enabled
4. Check out the developer console (press `F12`) when you start Obsidian. There might be some error messages.
5. Try reinstalling the plugin

**Comment by benadamstyles** [comment]
Ok nice, I'm guessing this helps?

![Uploading Screenshot 2023-03-27 at 14.19.36.png…]()

**Comment by benadamstyles** [comment]
Ok nice, I'm guessing this helps?

<img width="560" alt="Screenshot 2023-03-27 at 14 19 36" src="https://user-images.githubusercontent.com/4380655/227939952-13d8d37d-671f-4850-8b00-598a580124d5.png">

**Comment by benadamstyles** [comment]
Well, completely removing and reinstalling worked, so I'll close this. Thanks!
