### ISSUE TITLE
Additional task filter matches more than expected

### ISSUE THREAD

**Issue by Erik-Handeland** [ivan-lednev/obsidian-task-archiver#39]
Looks like you're using regex for tag matchings just wondering if this is intended behavior. I usually just use `#t` for my todo/tasks as it's shorter to write and takes up less space on each task line. However now if I have anyway other tag with start with t, its also gets caught. 

<img width="806" alt="image" src="https://user-images.githubusercontent.com/16601367/230012778-11b816f5-7ad4-4ceb-8818-81ded33eeafa.png">

**Comment by ivan-lednev** [comment]
Hello, @Erik-Handeland,

Yes, this behavior is intended. If you want to catch `#t`, but not, say, `#tomorrow`, you can use a pattern like this: `#t\b`
