### ISSUE TITLE
Archive "some" checked tasks

### ISSUE THREAD

**Issue by tonyxiao** [ivan-lednev/obsidian-task-archiver#40]
Right now the archive all checked tasks setting is all or nothing. 

<img width="842" alt="image" src="https://user-images.githubusercontent.com/696842/230899663-ca85afd7-e30d-46e9-95cb-ff136432c830.png">

However I would like to archive specific checks, such as `[x]` for done and `[-]` for cancelled (see obsidian tasks) and leave others in place. Would like there to be an option for configuring "which" checked tasks are archived instead.

**Comment by ivan-lednev** [comment]
Hello, @tonyxiao,

You can create a rule on the settings page and define the statuses that get handled by the plugin.

**Comment by tonyxiao** [comment]
Amazing, will check it out thank you!

**Comment by mathisgauthey** [comment]
> Right now the archive all checked tasks setting is all or nothing. 
> 
> <img width="842" alt="image" src="https://user-images.githubusercontent.com/696842/230899663-ca85afd7-e30d-46e9-95cb-ff136432c830.png">
> 
> 
> However I would like to archive specific checks, such as `[x]` for done and `[-]` for cancelled (see obsidian tasks) and leave others in place. Would like there to be an option for configuring "which" checked tasks are archived instead. 

If you still need assistance, I managed to do it by keeping the setting in your screenshot deactivated and using the following one : 
![Screenshot_20230504-062633.png](https://user-images.githubusercontent.com/46576952/236112589-70149805-b27f-42d8-9495-c5354fcf2a7d.png)

**Comment by mathisgauthey** [comment]
I don't know, sorry for late reply btw.

**Comment by ivan-lednev** [comment]
Closing this as resolved
