### ISSUE TITLE
Tasks not working

### ISSUE THREAD

**Issue by Emphazed** [ivan-lednev/obsidian-task-archiver#42]
Hello!

I tried different configuration, apprently no error in the console maybe I am missing something.
May it be a conflit with other plugin? Archiver seem to not be be working at all, neither with archive under headings or in Archive to a separate file.
I really would like to make it work, thanks

Picture of Archiver config:
![image](https://user-images.githubusercontent.com/128774548/232260386-68b0d1fc-1015-4eb3-b986-02b02cae6e68.png)

Picture of the name of my file I would like to Archive to:
![image](https://user-images.githubusercontent.com/128774548/232260415-55a00828-255a-47f9-b230-532ee3982698.png)

My current plugins where there could be a conflict;
![image](https://user-images.githubusercontent.com/128774548/232260430-bed62eb7-2b88-4f74-a706-a6a1d0908a05.png)
![image](https://user-images.githubusercontent.com/128774548/232260441-edb318ae-fe0b-4e2f-a913-f61e4cc4a557.png)

My console, no additional conflict when I try to archieve tasks (only some coming from fleeting notes):
![image](https://user-images.githubusercontent.com/128774548/232260510-46b02558-55f8-4dda-aace-873a3717b84c.png)

And the file I would like to paste them to:
![image](https://user-images.githubusercontent.com/128774548/232260523-0d4f8e8e-3530-4f64-9086-64a9548a8625.png)

Warmly

**Comment by ivan-lednev** [comment]
Hello, @Emphazed,

Please describe what you see when you try to archive tasks. Do tasks disappear from the file? Does a notification of some sort appear? Or just nothing happens? 

Have you tried to reinstall the plugin?

BTW, you've missed the point with the placeholders in the config. If you want to archive all the tasks to a specific file, you should write just the file name: `Archive tasks` instead of `{{Archive tasks}} (archive)`. You can use placeholders to send tasks to a file that includes the name of the current file. Say, if you're in `tasks.md` and your archive file path is `{{sourceFileName}} (archive)`, the tasks will get sent to `tasks (archive).md.

**Comment by Emphazed** [comment]
Thanks Ivan for your quick reponse it's higly appreciated.

It seems that nothing happend.

Yes I tried reinstall the plugin 3 times, I will try correcting the pass, effectively I missed the point, sorry I am not a programmer so not really use to specific typology.

Yes I am trying to make it disappear from the file and go to another file,

I tried correcting the pass like:
![image](https://user-images.githubusercontent.com/128774548/232330114-ea1a219e-5c97-49dc-aa56-31c2ce2c257d.png)

To make it go in the following file:
![image](https://user-images.githubusercontent.com/128774548/232330130-ebbf8d5d-df6f-44ae-a775-18a0faac0de4.png)

But nothing seems to happen, The console show no additional error after trying to archive.

Let me know if I can give you any more details which can help you to help me trying to find the issue, your plugin seems really cool!

Thanks,

Warmly

**Comment by ivan-lednev** [comment]
For starters, please share your config and I'll try to reproduce the issue. You can find it here: `<path to your vault>/.obsidian/plugins/obsidian-task-archiver/data.json`.

Please also send an example of a file in which the plugin doesn't work. You could create a file with a single completed task and see if it works there. 

Are you using the command palette to run the archiver? Which command are you using?

**Comment by Emphazed** [comment]
Okay thanks my issue was just a misundestanding of your plugin, I thought that:

![image](https://user-images.githubusercontent.com/128774548/232331776-9ba6d31a-c62f-42f1-be17-8c04ae8ed71c.png)

Was automatically archiving the task whitout running the command?

The plugin effectively work.

Is there a way to archive the task whit just checking the task?

Thanks for your support

**Comment by ivan-lednev** [comment]
Right now the closest thing to it is the command: `Toggle task done and archive it`. You can assign it to a hotkey and press the key when the cursor is on a line with a completed task. I'm going to add mouse support later.

**Comment by Emphazed** [comment]
Thanks sir!

 Hope to see this feature added in the future if it's not to hard for you to implement!

 I am all good, I think this topic could go to archive as well ^^ 

Thanks for your support and the plugin!

Cheers
