### ISSUE TITLE
Feature Request: allow collapsing of when then statements.

### ISSUE THREAD

**Issue by YousufSSyed** [ivan-lednev/obsidian-task-archiver#44]
They can take up lots of space in the setting viewport. I think there should be a setting for whether they're collapsed by default.

**Comment by ivan-lednev** [comment]
Hey, @YousufSSyed, this is available since 0.23.0. Currently, rules are expanded by default.

**Comment by YousufSSyed** [comment]
@ivan-lednev Can you make the arrows rotate to an up arrow when expanded, and to down arrows when collapsed?
