### ISSUE TITLE
Suggestion: Do not consider lists (numbered, bullet point, ...) as not-done tasks when including subtasks for archiving.

### ISSUE THREAD

**Issue by Glokta0** [ivan-lednev/obsidian-task-archiver#47]
Hi! Thank you @ivan-lednev for creating this wonderful and versatile and modifiable tool! It makes life a _lot_ easier.
There is one minor thing that stops me from being able to use it to its full potential. In my workflow, I often create bullet-points as a indented sub-level of tasks. These help me to keep track of notes as to how/why/... the task was completed.

However, if I enable

> Archive a task only if its subtasks are done

which I find immensely useful to not flood my archive in an unstructured way, these bullet points seem to represent "not-done tasks", meaning the parenting task does not get archived even though its completed.

I use the tasks-plugin including a hashtag to denote tasks, and yet, these (not-tagged) bulletpoints count as "not-completed". Thus, given the setting above being enabled, the task will not get archived.

Is there any chance this is problematic for others, too? It feels like a bug, because they are bullet points, not tasks.

---

Example of tasks that are not archived:
- [x] # Task TaskDescription1
    - How this was completed 
- [x] # Task TaskDescription2
    - [ ] Step 1

Example of task that is archived 
- [x] # Task TaskDescription3
    - [x] Step 1

---

Task 3 would be expected to work, and Task 2 would be expected not wo work.

However, Task 1, I would like to archive also, as it does not include any open To-Dos, but only "notes".

However, this might be subjective and is impacted by my personal workflow. Take it as an inspiration and decide whether you would think such a change valuable.

Cheers, and again, thanks for creating this plug-in!

**Comment by ivan-lednev** [comment]
Hi, @Glokta0,

Thank you for your input! This is definitely a bug, and it's fixed in 0.23.2.
