### ISSUE TITLE
Archiving by day rather than week

### ISSUE THREAD

**Issue by tonyxiao** [ivan-lednev/obsidian-task-archiver#5]
in the screenshot in readme it shows date nesting under the week, but when I installed the plugin no such option is available. If I have to choose one I'd like to archive per day, rather than per week. 

Would like to have the option for such I mean.

**Comment by ivan-lednev** [comment]
Hello @tonyxiao,
thank you for raising the issue! 
I addressed it in the [new version of the plugin](https://github.com/ivan-lednev/obsidian-task-archiver/releases/tag/0.3.0). Please update the plugin to get access the new option.
