### ISSUE TITLE
Issue when creating new lines on android

### ISSUE THREAD

**Issue by mathisgauthey** [ivan-lednev/obsidian-task-archiver#51]
Hi ! Following an [issue](https://forum.obsidian.md/t/android-gboard-cant-create-new-line-in-notes-return-enter/55219/30) that occured some weeks ago, I created an [help topic](https://forum.obsidian.md/t/android-new-line-not-working-while-on-a-word-using-gboard-on-pixel-7/60860) on the obsidian forum as well because the issue was still occurring on my phone, but only with my plugins.

I disabled my plugins one by one and it turns out the issue is related to the archiver plugin !

The issue : Can't create a new line while on a word. It works if I input a space, if I add some punctuation, or select the begining of the next line. But I can't use a backspace on mobile otherwise.

Infos : 
- Pixel 7
- Android 13, May 5 2023 Security Update
- Obsidian 1.4.5 (Build 104)
- Gboard 12.9.20.521739039-release-arm64-v8a

**Comment by mathisgauthey** [comment]
It seems a recent Gboard update or the uninstallation of the language tool plugin made it stop, I have no more complain about this issue.

**Comment by ivan-lednev** [comment]
Hello, @mathisgauthey! 

Thank you for taking the time to close the issue ❤️
