### ISSUE TITLE
Archive to separate file does not honour date format

### ISSUE THREAD

**Issue by Kolossi** [ivan-lednev/obsidian-task-archiver#52]
- Plugin version: 0.23.2
- Obsidian version: v1.3.5 (windows desktop)
- Windows 11 22H2 (OS Build 22621.1848)

When using "Archive to a separate file" option, with File name spec `2023/Daily/{{date}}` and under "Configure variables" both "Date format" and "obsidian-taks completed date format" set to `YYYY-MM-DD_ddd` the created filename is in format `YYYY-MM-DD`

Example screen grab, with expected existing filename `2023-06-24_Sat`, archived tasks are put in newly created file `2023-06-24`.  (Same happend if expected file does not exist:

![image](https://github.com/ivan-lednev/obsidian-task-archiver/assets/5367728/fe501640-2146-4ea6-9280-e837dc9f1431)

BTW Thanks for the great plugin, exactly what I needed.

**Comment by gKucAdmin** [comment]
Same issue here.

**Comment by ivan-lednev** [comment]
Hello, @Kolossi, please update the plugin and re-check.

**Comment by Kolossi** [comment]
Yup confirm fixed.  Thanks. @ivan-lednev
