### ISSUE TITLE
Feature Request: Optionally use daily notes core plugin when archiving to a separate file

### ISSUE THREAD

**Issue by Kolossi** [ivan-lednev/obsidian-task-archiver#53]
When using the "Archive to a separate file" option, ideally give the option to use the core "daily notes" plugin to create the file if it doesn't exist so that the relevant template and file location specified there is picked up.

Alternatively, at least just give the option to specify a template for the created file within Archiver, and use the existing filename given in the "archive to a separate file" option ([when fixed](https://github.com/ivan-lednev/obsidian-task-archiver/issues/52) :-) )

Thanks again for the great plugin.

**Comment by ivan-lednev** [comment]
Hey, @Kolossi, the issue you referenced got fixed. Additionally, now you have an option to archive tasks to your daily notes and use the template from daily note settings if the note does not exist:
![image](https://github.com/ivan-lednev/obsidian-task-archiver/assets/41428836/f8961c85-c6b9-4d20-b0a0-652cc2cfeca3)

**Comment by Kolossi** [comment]
Perfect!

Thanks again @ivan-lednev 

Coffees donated :-)
