### ISSUE TITLE
Feature Request: Instead of a toggle to archive all statuses other than [x] allow specification of multiple statuses

### ISSUE THREAD

**Issue by macbikegeek** [ivan-lednev/obsidian-task-archiver#55]
Instead of a toggle to archive all statuses other than [x] allow specification of multiple statuses to be selected for archiving.
Use case: [-] is used by some notations to mean the task was canceled instead of finished. These should be archived because they are done with. Most of the custom statuses are clarifications of some characteristic of the task while it is unfinished and thus should not be archived.

**Comment by ivan-lednev** [comment]
@macbikegeek, have you tried adding a custom rule for the statuses you want to handle? https://github.com/ivan-lednev/obsidian-task-archiver#rules

**Comment by macbikegeek** [comment]
Thanks, no, I didn't understand them to do that. I'll try it and report back. Thanks!

**Comment by macbikegeek** [comment]
I set up a rule for just - status and the preview shows that as what will be processed. I have no file mask. I have this for the target of the move: {{sourceFilePath}} #Archived. When I run the archive tasks command, the task is removed completely from the note. I assume I'm doing something wrong.

**Comment by ivan-lednev** [comment]
@macbikegeek you specified both a file and a heading. Only the file can be specified here:
![image](https://github.com/ivan-lednev/obsidian-task-archiver/assets/41428836/f74aaced-85f0-49e7-9ed5-71b07b328ab1)

So to archive it to the same file, use `{{sourceFilePath}}`

To configure the heading, check out the "Archive under headings" option.

**Comment by ivan-lednev** [comment]
Closing this as stale.
