### ISSUE TITLE
Run ‘Archive tasks in file’ will remove the space at the beginning of each line，this may remove code indentation

### ISSUE THREAD

**Issue by ribber** [ivan-lednev/obsidian-task-archiver#56]
there is some dataviewjs code in my note，and this bug will remove code indentation

for example

```dataviewjs
for (var i = 0; i < 10; i++) {
    console.log(123)
}
```

will become

```dataviewjs
for (var i = 0; i < 10; i++) {
console.log(123)
}
```

**Comment by ivan-lednev** [comment]
Hello, @ribber, please update the plugin, re-check and let me know if this helps.

**Comment by ribber** [comment]
this bug is fixed，thank you very much
