### ISSUE TITLE
Question: Treating completed recurring tasks differently from completed non-recurring tasks?

### ISSUE THREAD

**Issue by FilSalustri** [ivan-lednev/obsidian-task-archiver#57]
Is there a way to archive completed _recurring_ tasks differently from completed _non-recurring_ tasks?

In my case, I prefer to delete completed recurring tasks but archive completed non-recurring tasks. Both types can appear in a given note of mine.

**Comment by ivan-lednev** [comment]
Hello, @FilSalustri, with the new version of the plugin you can create a rule like that:
![image](https://github.com/ivan-lednev/obsidian-task-archiver/assets/41428836/eb0db044-a4f9-4f0d-b5fb-0192f5c945de)

In the text patterns, we use the emoji that obsidian-tasks uses to mark recurrent tasks.

Let me know if this solves your issue!

**Comment by FilSalustri** [comment]
Oh, this is very interesting!
I'll investigate it ASAP.
Thanks very much for this!
