### ISSUE TITLE
Bug: Archiver breaks frontmatter/the Property Editor in Obsidian 1.4.2

### ISSUE THREAD

**Issue by WebInspectInc** [ivan-lednev/obsidian-task-archiver#59]
Weird issue, but it's been happening to me a lot lately: whenever I archive tasks in Obsidian 1.4.2, it breaks the property editor.

IF I have a "tags" property on the file (I assume any list of items, but I've only tested tags), and I run the "archive tasks in this file" command, it breaks the tags by adding tab characters to the YAML.

Just to make sure, I tested in the Sandbox vault. Here are steps to recreate:

- Open sandbox vault
- Install and enable Archiver plugin
- Open any file, add multiple tags
- Run the archive tasks command
- The YAML is changed to invalid YAML and appears in the file
- The result looks like this:

![Screenshot from 2023-08-09 09-16-58](https://github.com/ivan-lednev/obsidian-task-archiver/assets/963985/3aa00d78-fe14-4630-a5a0-1995377ff874)

The Archiver plugin adds an additional tab character for every additional tag, which is quite weird and annoying.

**Comment by kmaustral** [comment]
I've found this issue with any YAML property that is in list format.

**Comment by Drakemoor** [comment]
Not only that but it doesn't archive the tasks in the file if there is a list property in the YAML.

**Comment by Drakemoor** [comment]
Is there a workaround this?

**Comment by ivan-lednev** [comment]
Hello @WebInspectInc , please update the plugin and re-check. Let me know if this helps!

**Comment by kmaustral** [comment]
Works perfectly now. Thanks Ivan.
