### ISSUE TITLE
Ability to do a negative filter

### ISSUE THREAD

**Issue by tristil** [ivan-lednev/obsidian-task-archiver#71]
I might be missing something. I want to filter for e.g. `-#recurring`

**Comment by ivan-lednev** [comment]
This is straight from Dataview docs:
> Querying from #food and !#fastfood will only return pages that contain #food but does not contain #fastfood.

[Source](https://blacksmithgu.github.io/obsidian-dataview/reference/sources/)

**Comment by ivan-lednev** [comment]
Fix: oops, I didn't notice you created an issue in the archiver plugin. Sorry for the confusion 😆 Please clarify where do you want this filter to work

**Comment by ivan-lednev** [comment]
This field accepts a regular expression. Try this:
```js
^(?:(?!#recurring).)*$
```

Or with multiple tags:
```js
^(?:(?!#recurring|#some-other).)*$
```

**Comment by tristil** [comment]
Thank you! I actually did experiment with negative lookahead but I guess I needed the start and end line anchors too. That solves my problem.
