### ISSUE TITLE
What does "archive all checked tasks" really do?

### ISSUE THREAD

**Issue by FilSalustri** [ivan-lednev/obsidian-task-archiver#78]
There's a settings toggle to "archive all checked tasks".
But examples shown on the setting suggest it will archive all checked tasks that signify an "end state" (i.e., done, cancelled, delegated, etc.).

So my question is, will this option archive a task marked, for instance, as "[/]" (i.e., in progress), or "[b]" (i.e., bookmark?

Ideally, it would be possible for a user to specify which special characters trigger the archiving operation, but I don't see that in the settings.

**Comment by ivan-lednev** [comment]
You can define which chars trigger archiving by creating a rule like so:
![image](https://github.com/ivan-lednev/obsidian-task-archiver/assets/41428836/806cd7e8-0680-4550-997a-12b6c99434ce)

**Comment by FilSalustri** [comment]
Thanks very much. That'll work fine for me.
