### ISSUE TITLE
After archive, the subtasks become indented by two levels, resulting in rendering abnormalities.

### ISSUE THREAD

**Issue by ribber** [ivan-lednev/obsidian-task-archiver#90]
before archive

![image](https://github.com/ivan-lednev/obsidian-task-archiver/assets/5986011/6842447a-3811-411c-91a4-096da1748e04)

after archive

![image](https://github.com/ivan-lednev/obsidian-task-archiver/assets/5986011/5b4c761c-c74b-40d8-9878-29184bdf8225)

**Comment by ivan-lednev** [comment]
Hello, @ribber

1. What do you have `Settings -> Editor`
![image](https://github.com/ivan-lednev/obsidian-task-archiver/assets/41428836/f6694e2d-e0e5-425d-b025-4b4c07fc3915)
2. Are you using a linter plugin or another editor to edit your files?

**Comment by ribber** [comment]
![image](https://github.com/ivan-lednev/obsidian-task-archiver/assets/5986011/ddf5ada6-adc4-4afc-a878-befb030663d7)

I did not use a lint plugin or any other editor.

**Comment by ivan-lednev** [comment]
Can you share your plugin config? It's in `<your-vault>/.obsidian/plugins/obsidian-task-archiver/data.json`.

**Comment by ribber** [comment]
[data.json](https://github.com/ivan-lednev/obsidian-task-archiver/files/14737420/data.json)

**Comment by ribber** [comment]
I'm sorry, I found my "Tab indent size" is 6, and When I changed this setting to 2, the execution was right
